services:
  postgres:
    image: postgres:16
    container_name: medappoint-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-medappoint}
      POSTGRES_USER: ${DB_USER:-medapp}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-medpass}
      TZ: ${TZ:-Asia/Kuala_Lumpur}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_data: {}
